"""Add contact_wechat field to links

Revision ID: 18c8f83f738e
Revises: 001
Create Date: 2025-11-23 16:42:28.745106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18c8f83f738e'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_access_logs_accessed_at'), table_name='access_logs')
    op.drop_index(op.f('idx_access_logs_link_id'), table_name='access_logs')
    op.create_index(op.f('ix_access_logs_accessed_at'), 'access_logs', ['accessed_at'], unique=False)
    op.create_index(op.f('ix_access_logs_id'), 'access_logs', ['id'], unique=False)
    op.create_index(op.f('ix_access_logs_link_id'), 'access_logs', ['link_id'], unique=False)
    op.drop_index(op.f('idx_links_created_by'), table_name='links')
    op.drop_index(op.f('idx_links_is_active'), table_name='links')
    op.drop_index(op.f('idx_links_short_code'), table_name='links')
    op.drop_constraint(op.f('links_short_code_key'), 'links', type_='unique')
    op.create_index(op.f('ix_links_created_by'), 'links', ['created_by'], unique=False)
    op.create_index(op.f('ix_links_id'), 'links', ['id'], unique=False)
    op.create_index(op.f('ix_links_is_active'), 'links', ['is_active'], unique=False)
    op.create_index(op.f('ix_links_short_code'), 'links', ['short_code'], unique=True)
    op.drop_index(op.f('idx_users_role'), table_name='users')
    op.drop_index(op.f('idx_users_username'), table_name='users')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('idx_users_role'), 'users', ['role'], unique=False)
    op.drop_index(op.f('ix_links_short_code'), table_name='links')
    op.drop_index(op.f('ix_links_is_active'), table_name='links')
    op.drop_index(op.f('ix_links_id'), table_name='links')
    op.drop_index(op.f('ix_links_created_by'), table_name='links')
    op.create_unique_constraint(op.f('links_short_code_key'), 'links', ['short_code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_links_short_code'), 'links', ['short_code'], unique=False)
    op.create_index(op.f('idx_links_is_active'), 'links', ['is_active'], unique=False)
    op.create_index(op.f('idx_links_created_by'), 'links', ['created_by'], unique=False)
    op.drop_index(op.f('ix_access_logs_link_id'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_id'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_accessed_at'), table_name='access_logs')
    op.create_index(op.f('idx_access_logs_link_id'), 'access_logs', ['link_id'], unique=False)
    op.create_index(op.f('idx_access_logs_accessed_at'), 'access_logs', ['accessed_at'], unique=False)
    # ### end Alembic commands ###
