"""add_is_banned_to_links

Revision ID: 629801496aba
Revises: 981237377003
Create Date: 2025-11-23 17:42:16.411183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '629801496aba'
down_revision: Union[str, None] = '981237377003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('is_banned', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.create_index(op.f('ix_links_is_banned'), 'links', ['is_banned'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_is_banned'), table_name='links')
    op.drop_column('links', 'is_banned')
    # ### end Alembic commands ###
