"""add_expire_at_and_max_visits_to_links

Revision ID: 81fd889e48f6
Revises: 18c8f83f738e
Create Date: 2025-11-23 17:18:14.913422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81fd889e48f6'
down_revision: Union[str, None] = '18c8f83f738e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('expire_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('links', sa.Column('max_visits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'max_visits')
    op.drop_column('links', 'expire_at')
    # ### end Alembic commands ###
