"""add_is_deleted_to_links

Revision ID: 981237377003
Revises: 81fd889e48f6
Create Date: 2025-11-23 17:34:16.160830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '981237377003'
down_revision: Union[str, None] = '81fd889e48f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.create_index(op.f('ix_links_is_deleted'), 'links', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_is_deleted'), table_name='links')
    op.drop_column('links', 'is_deleted')
    # ### end Alembic commands ###
