"""add title to links

Revision ID: e345ace75354
Revises: 4efce910ef21
Create Date: 2025-11-24 17:39:28.674763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e345ace75354'
down_revision: Union[str, None] = '4efce910ef21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('title', sa.String(length=100), nullable=True, comment='链接标题'))
    op.alter_column('links', 'short_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('links', 'short_code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('links', 'title')
    # ### end Alembic commands ###
